# This is a basic workflow to help you get started with Actions
name: Ping-CI-Pipeline

# Controls when the workflow will run
on:
  # Triggers the workflow on pull request events on main branch
  pull_request:
    types: [opened, reopened, synchronize ]
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab for the development purpose
  workflow_dispatch:

jobs:
  lacework-scanning:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Scan PingFederate container image for vulnerabilites
        uses: lacework/lw-scanner-action@v1.4.1
        with:
          LW_ACCOUNT_NAME: ${{ secrets.LW_ACCOUNT_NAME }}
          LW_ACCESS_TOKEN: ${{ secrets.PVS_LW_ACCESS_TOKEN }}
          image_name: '337141981580.dkr.ecr.eu-west-2.amazonaws.com/tsb_sandbox1_ecr'
          image_tag: pingfederate_11.3.0-latest
          SAVE_RESULTS_IN_LACEWORK: true
          RESULTS_IN_GITHUB_SUMMARY: true
          SCAN_LIBRARY_PACKAGES: true
          args: --json
      
      - name: Scan PingDirectory container image for vulnerabilites
        uses: lacework/lw-scanner-action@v1.4.1
        with:
          LW_ACCOUNT_NAME: ${{ secrets.LW_ACCOUNT_NAME }}
          LW_ACCESS_TOKEN: ${{ secrets.PVS_LW_ACCESS_TOKEN }}
          image_name: '337141981580.dkr.ecr.eu-west-2.amazonaws.com/tsb_sandbox1_ecr'
          image_tag: pingdirectory_2307-9.3.0.0
          SAVE_RESULTS_IN_LACEWORK: true
          RESULTS_IN_GITHUB_SUMMARY: true
          SCAN_LIBRARY_PACKAGES: true
          args: --json