{{- $top := . -}}
{{- $prodName := "pingdirectory" -}}
{{- $mergedValues := merge (index $top.Values "pingdirectory") $top.Values.global -}}
{{- $params := list $top $mergedValues -}}

{{- if $mergedValues.services.loadBalancerServicePerPod -}}
  {{- range $i := until (int $mergedValues.container.replicaCount) }}
---
{{ $podName := (print (include "pinglib.fullname" $params) "-" $i) -}}
    {{- $hostname := (print (include "pinglib.fullname" $params) "-" $i $mergedValues.services.loadBalancerExternalDNSHostnameSuffix) -}}
    {{- include "pingdirectory.service-load-balancer" (list $top $mergedValues $podName $hostname $podName)  -}}
  {{- end -}}
{{- end -}}


{{- define "pingdirectory.service-load-balancer" -}}
{{- $top := index . 0 -}}
{{- $v := index . 1 -}}
{{- $serviceName := index . 2 -}}
{{- $hostname := index . 3 -}}
{{- $podName := index . 4 -}}
apiVersion: v1
kind: Service
metadata:
  {{- include "pinglib.metadata.labels" . | nindent 2  -}}
  {{- if $v.annotations -}}
    {{- include "pinglib.metadata.annotations" . | nindent 2 -}}
  {{- else }}
  annotations:
  {{- end }}
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    external-dns.alpha.kubernetes.io/hostname: {{ $hostname }}
  name: {{ $serviceName }}
spec:
  type: LoadBalancer
  selector:
    statefulset.kubernetes.io/pod-name: {{ $podName }}
  {{/* publishNotReadyAddresses must be true for pods to communicate via load balancers */}}
  publishNotReadyAddresses: true
  sessionAffinity: None
  ports:
  {{- range $serviceName, $val := $v.services }}
  {{- if kindIs "map" $val }}
  {{- if $val.loadBalancerService }}
    - name: {{ $serviceName }}
      port: {{ required "containerPort is required for services with loadBalancerService:true" $val.containerPort }}
      protocol: {{ default "TCP" $val.protocol }}
  {{- end }}
  {{- end }}
  {{- end }}
{{- end -}}
